### ISSUE TITLE
Dark Mode - Text color "Start typing to search..." in the Flight Map filtering

### ISSUE THREAD

**Issue by DarrianCZE** [DarrianCZE/vamsys-v5-custom-css#2]
Text color "Start typing to search..." in the Flight Map filtering, when the filter is highlighted, doesn't change to the primary or secondary color. I unfortunately had no luck finding out why.

**Comment by DarrianCZE** [comment]
Sadly, I have no clue how to fix this so far...

**Comment by LukasJK** [comment]
Don't think this is needed anymore as I've fixed it on vAMSYS end. But if you want to override:

```css
.choices__input:is(.dark *)::-moz-placeholder {
    color: var(--tw-body-color);
}
.choices__input:is(.dark *)::placeholder {
    color: var(--tw-body-color);
}
